export interface FirstDayInsuranceOption {
  value: string;
  label: string;
}

// Fallback options mirror the full insurance source list shared by business.
export const FIRST_DAY_INSURANCE_FALLBACK_OPTIONS: FirstDayInsuranceOption[] = [
  { value: "-1", label: "All" },
  { value: "-2", label: "Undefined" },
  { value: "42089", label: "Aetna Better Health of NY (AHC)" },
  { value: "42085", label: "Aetna Better Health of NY (MTN)" },
  { value: "42087", label: "Aetna Better Health of NY (PDE)" },
  { value: "42086", label: "Aetna Better Health of NY (STI)" },
  { value: "4990", label: "Aetna Better Health RN" },
  { value: "20874", label: "Aetna CDPAP" },
  { value: "4675", label: "Agewell Medicaid Advanage Plus" },
  { value: "4999", label: "Alpha care" },
  { value: "102", label: "Alpine" },
  { value: "8164", label: "Always" },
  { value: "2568", label: "Americare" },
  { value: "9126", label: "Americare Home Care" },
  { value: "18972", label: "Amerigroup NYC CDPAP" },
  { value: "4993", label: "Amerigroup-Empire Blue Cross LCHSA" },
  { value: "14005", label: "Anthem CDPAP(Integra)" },
  { value: "5069", label: "Anthem(Integra)" },
  { value: "4997", label: "ARCHCARE COMMUNITY LIFE" },
  { value: "67824", label: "Archcare Senior Life-PACE" },
  { value: "4994", label: "Bankers Conesco Life Insurance Company" },
  { value: "26496", label: "Bikur Cholim Chesed Organization" },
  { value: "9224", label: "Blue Cross Blue Shield of Florida" },
  { value: "37903", label: "CALAVARY HOSPITAL HOSPICE" },
  { value: "25146", label: "Caring Hospice Services" },
  { value: "16560", label: "Caringkind" },
  { value: "15190", label: "Cassena Care At Home / Centerlight CHHA" },
  { value: "17709", label: "Center Light CHHA" },
  { value: "5003", label: "CenterLight RN" },
  { value: "44604", label: "CenterLight HealthCare (PACE) (AHC)" },
  { value: "63239", label: "CenterLight HealthCare (PACE) (AMD)" },
  { value: "44605", label: "CenterLight HealthCare (PACE) (MTN)" },
  { value: "44607", label: "CenterLight HealthCare (PACE) (PDE)" },
  { value: "44606", label: "CenterLight HealthCare (PACE) (STI)" },
  { value: "4998", label: "CENTERS PLAN for a HEALTHY LIV" },
  { value: "4995", label: "CNH" },
  { value: "4996", label: "Cobble Hill" },
  { value: "16070", label: "Continental General" },
  { value: "10013", label: "Elderplan CDPAS PMPM" },
  { value: "29870", label: "Elderplan MJHS (AHC)" },
  { value: "29866", label: "Elderplan MJHS (MTN)" },
  { value: "29868", label: "Elderplan MJHS (PDE)" },
  { value: "29867", label: "Elderplan MJHS (STI)" },
  { value: "5004", label: "Elderplan RN" },
  { value: "56456", label: "ElderServe Health (AHC)" },
  { value: "56458", label: "ElderServe Health (PDE)" },
  { value: "56457", label: "ElderServe Health (STI)" },
  { value: "5002", label: "Emblem Health" },
  { value: "74159", label: "Emerest GUIDE (AHC)" },
  { value: "6858", label: "Excellent Home Care" },
  { value: "890", label: "Excellent Home Care Services" },
  { value: "1253", label: "Extended Home Care" },
  { value: "6587", label: "Extended Home Care" },
  { value: "5622", label: "Extended Managed Long Term Care" },
  { value: "63891", label: "Extended Nursing Personnel CHHA, LLC" },
  { value: "50417", label: "Fidelis Care (AHC)" },
  { value: "50418", label: "Fidelis Care (MTN)" },
  { value: "50420", label: "Fidelis Care (PDE)" },
  { value: "50419", label: "Fidelis Care (STI)" },
  { value: "4971", label: "Fidelis care RN" },
  { value: "9563", label: "Four Season CHHA" },
  { value: "8879", label: "Four Seasons Nursing Rehab Center" },
  { value: "5000", label: "Gentiva" },
  { value: "71349", label: "Genworth Life & Annuity" },
  { value: "2706", label: "Girling Health Care Of New York" },
  { value: "4970", label: "Guildnet" },
  { value: "70403", label: "HAMASPIK" },
  { value: "9320", label: "Health Care Partners, MSO" },
  { value: "5001", label: "Health First RN" },
  { value: "58620", label: "Healthfirst (AHC)" },
  { value: "58622", label: "Healthfirst (PDE)" },
  { value: "58621", label: "Healthfirst (STI)" },
  { value: "6379", label: "Hebrew Elderserve" },
  { value: "4986", label: "HHH Choices" },
  { value: "13935", label: "Hillside Manor CHHA" },
  {
    value: "64083",
    label: "Holocaust Survivors Program Self Help Community Se",
  },
  { value: "5039", label: "Independence Care System, Inc" },
  { value: "57129", label: "John Hancock Life & Health" },
  { value: "25374", label: "Medical Indemnity Fund" },
  { value: "1645", label: "METRO JEWISH" },
  { value: "5005", label: "METROPLUS HEALTH" },
  { value: "5182", label: "MJHS HOSPICE" },
  { value: "73543", label: "Molina Health New York (AHC)" },
  { value: "73547", label: "Molina Health New York (AMD)" },
  { value: "73544", label: "Molina Health New York (MTN)" },
  { value: "73546", label: "Molina Health New York (PDE)" },
  { value: "73545", label: "Molina Health New York (STI)" },
  { value: "71435", label: "New York State Insurance Fund" },
  { value: "63344", label: "NHTD Waiver Service" },
  { value: "15571", label: "North Shore LIJ CHHA" },
  { value: "6474", label: "North Shore LIJ Health Plan" },
  { value: "4977", label: "NY Congregational" },
  { value: "7881", label: "NYCTA Workers Compensation" },
  { value: "4976", label: "PARKER JEWISH" },
  { value: "73386", label: "Parker Jewish Institute CHHA and Hospice" },
  { value: "2432", label: "Personal Touch" },
  { value: "5094", label: "Personal Touch Home Care" },
  { value: "52506", label: "PHP Partner Health Plan" },
  { value: "73832", label: "PREFERRED CERTIFIED" },
  { value: "4975", label: "Prime Home Care" },
  { value: "262", label: "Prime Home Health Services" },
  { value: "25546", label: "Private Duty Experts" },
  { value: "4498", label: "Private Pay" },
  { value: "1", label: "Revival Home Health Care" },
  { value: "68457", label: "Revival Home Health Care" },
  { value: "4987", label: "RIVERSPRING RN" },
  { value: "8048", label: "Royal Care Certified" },
  { value: "66144", label: "Royal Care Certified of NY" },
  { value: "4989", label: "Senior Health Partners" },
  { value: "31308", label: "Senior Whole Health (AHC)" },
  { value: "31309", label: "Senior Whole Health (MTN)" },
  { value: "31311", label: "Senior Whole Health (PDE)" },
  { value: "31310", label: "Senior Whole Health (STI)" },
  { value: "5458", label: "Senior Whole Health RN" },
  { value: "14796", label: "Shining Star Home Care CHHA" },
  { value: "39758", label: "SWHNY-MLTC (AHC)" },
  { value: "39754", label: "SWHNY-MLTC (MTN)" },
  { value: "39756", label: "SWHNY-MLTC (PDE)" },
  { value: "39755", label: "SWHNY-MLTC (STI)" },
  { value: "63400", label: "TBI WAIVER" },
  { value: "8285", label: "TestContract" },
  { value: "5008", label: "United Health Community Plan" },
  { value: "4093", label: "Village Care" },
  { value: "27347", label: "Village Care Telehealth" },
  { value: "4973", label: "VillageCareMAX" },
  { value: "6590", label: "VNS CHOICE RN" },
  { value: "55890", label: "VNS Health Health Plans (AHC)" },
  { value: "8877", label: "VNSNY Choice Fida" },
  { value: "8059", label: "Wellbound" },
  { value: "5009", label: "WellCare" },
  { value: "42185", label: "Your Choice at Home" },
  { value: "7343", label: "YOUR CHOICE AT HOME, INC(CHHA)" },
];
