import { IncidentOption } from "./IncidentTypes";

function toOptions(values: string[]): IncidentOption[] {
  return values.map((value) => ({ value, label: value }));
}

const HOSPITALIZATION_VENDOR_CONTRACT_VALUES = [
  "Aetna Better Health of NY",
  "Agewell Medicaid Advanage Plus",
  "Alpine",
  "Americare",
  "Amerigroup-Empire Blue Cross LCHSA",
  "Anthem (Integra)",
  "ARCHCARE COMMUNITY LIFE",
  "Bankers Conesco Life Insurance Company",
  "Bikur Cholim Chesed Organization",
  "Caring Hospice Services",
  "Center Light CHHA",
  "CENTERS PLAN for a HEALTHY LIV",
  "Continenetal General",
  "Elderplan MJHS",
  "Empire BCBS(Integra)",
  "Excellent Home Care Services",
  "Extended Home Care",
  "Fidelis Care",
  "Four Season CHHA",
  "Girling Health Care Of New York",
  "Healthfirst",
  "Holocaust Survivors Program Self Help Community",
  "Home First-Elderplan RN",
  "John Hancock Life & Health",
  "Medical Indemnity Fund",
  "METRO JEWISH",
  "METROPLUS HEALTH",
  "MJHS HOSPICE",
  "Parker Jewish",
  "Personal Touch",
  "PHP Partner Health Plan",
  "Prime Home Health Services",
  "Private Pay",
  "RiverSpring Health Plans",
  "Royal Care Certified",
  "Senior Whole Health",
  "Shining Star Home Care CHHA",
  "SWHNY-MLTC",
  "VillageCareMAX",
  "VNS Health",
  "Other",
];

const DEATH_VENDOR_VALUES = [
  "Always Home Care",
  "AHC – New York",
  "AHC -- Richmond",
  "Private Duty Expert",
  "Always NHTD/TBI",
  "Edison Home Health Care",
  "Allied Home Care",
  "FreedomCare",
  "PPL CDPAP",
  "Elite Home Health Care",
  "Edison Certified Home Health Agency",
  "HCS Home Care",
  "Partners In Care",
  "Preferred Home Care of NY",
  "Bestcare",
  "Caregivers Home Care",
  "Galaxy Home Care",
  "Helping U Homecare",
  "Prime Home Health Services",
  "Chinese-American Planning Council Home Attendant Program",
  "Sunnyside Community Services",
  "RiverSpring Licensed Home Care",
  "CenterLight Teamcare",
  "VNS Health",
  "Fidelis Care",
  "Healthfirst",
  "MetroPlusHealth",
  "Elderplan",
  "Hamaspik Choice",
  "Independence Care System",
  "Senior Health Partners",
  "VillageCareMAX",
  "ArchCare",
  "Molina Healthcare",
  "UnitedHealthcare Community Plan",
  "EmblemHealth",
  "Affinity by Molina",
  "WellCare",
  "Anthem Blue Cross Blue Shield",
  "Medicaid Pending",
  "Family member reported",
  "Hospital staff reported",
  "Other answer",
];

const HOSPITAL_NAME_VALUES = [
  "Bellevue Hospital Center",
  "BronxCare Health System",
  "Brookdale Hospital Medical Center",
  "Coney Island Hospital",
  "Elmhurst Hospital Center",
  "Flushing Hospital Medical Center",
  "Harlem Hospital Center",
  "Interfaith Medical Center",
  "Jamaica Hospital Medical Center",
  "Kings County Hospital Center",
  "Lenox Hill Hospital",
  "Long Island Jewish Medical Center",
  "Lutheran Medical Center",
  "Maimonides Medical Center",
  "Maimonides Midwood Community Hospital",
  "Memorial Sloan Kettering Cancer Center",
  "Montefiore Medical Center Moses Campus",
  "Montefiore Medical Center Weiler Campus",
  "Mount Sinai Beth Israel",
  "Mount Sinai Brooklyn",
  "Mount Sinai Hospital",
  "Mount Sinai Morningside",
  "Mount Sinai Queens",
  "Mount Sinai West",
  "NewYork-Presbyterian Brooklyn Methodist Hospital",
  "NewYork-Presbyterian/Columbia University Irving Medical Center",
  "NewYork-Presbyterian/Lower Manhattan Hospital",
  "NewYork-Presbyterian Queens",
  "NewYork-Presbyterian/Weill Cornell Medical Center",
  "North Central Bronx Hospital",
  "NYC Health + Hospitals/Gotham Health",
  "NYU Langone Hospital-Brooklyn",
  "NYU Langone Hospital-Long Island",
  "NYU Langone Hospital-Manhattan",
  "NYU Langone Tisch Hospital",
  "NYU Langone Orthopedic Hospital",
  "One Brooklyn Health Brookdale",
  "One Brooklyn Health Interfaith",
  "One Brooklyn Health Kingsbrook Jewish Medical Center",
  "Richmond University Medical Center",
  "Staten Island University Hospital North",
  "Staten Island University Hospital South",
  "SUNY Downstate Medical Center",
  "The Brooklyn Hospital Center",
  "The Mount Sinai Hospital Emergency Department",
  "University Hospital at Downstate",
  "UPMC Chautauqua",
  "Westchester Medical Center",
  "White Plains Hospital",
  "Wyckoff Heights Medical Center",
  "Good Samaritan Hospital Medical Center",
  "St Catherine of Siena Hospital",
  "St Charles Hospital",
  "St Francis Hospital & Heart Center",
  "St John's Episcopal Hospital",
  "St Joseph Hospital",
  "Huntington Hospital",
  "Long Island Community Hospital",
  "Nassau University Medical Center",
  "North Shore University Hospital",
  "Plainview Hospital",
  "South Shore University Hospital",
  "Stony Brook University Hospital",
  "South Nassau Communities Hospital",
  "Cohen Children's Medical Center",
  "Hospital for Special Surgery",
  "Jacobi Medical Center",
  "Lincoln Medical and Mental Health Center",
  "Other",
];

const HOSPITALIZATION_REASON_VALUES = [
  "Abdominal Pain",
  "Altered Mental Status",
  "Cardiac",
  "Chest Pain",
  "Dehydration",
  "Difficulty Breathing",
  "Dizziness",
  "Fall / Accident",
  "Fever",
  "GI Symptoms",
  "Headache",
  "Hyperglycemia",
  "Hypertension",
  "Hypoglycemia",
  "Infections",
  "Medication Reaction",
  "Neurological Symptoms",
  "Pain Management",
  "Planned Hospitalization",
  "Psychiatric / Behavioral",
  "Renal / Urologic",
  "Respiratory Distress",
  "Seizure",
  "Stroke Symptoms",
  "Syncope",
  "Trauma / Injury",
  "Unwell (Malaise)",
  "Wound",
  "Other answer",
];

const INFECTION_TYPE_VALUES = [
  "COVID-19",
  "Pneumonia",
  "Respiratory Infection (any, but not Pneumonia )",
  "UTI",
  "Skin/Wound",
  "Other answer",
];

const SOURCE_OF_INFORMATION_VALUES = [
  "Family, Friends, Client Emergency Contact",
  "Vendor",
  "Social Worker, Hospital Employee",
  "Caregiver (PCA, HHA, HCSS)",
  "Other answer",
];

const FALL_ACCIDENT_TYPE_VALUES = [
  "Bruises / Cuts",
  "Car Accident",
  "Trip / Fall",
  "Fire / Burns",
  "Patient Abuse / Physical Violence",
  "Poisoning",
  "Pressure ulcer / Wound",
  "Other answer",
];

const YES_NO_UNKNOWN_VALUES = ["Yes", "No", "Unknown"];

const YES_NO_VALUES = ["Yes", "No"];

const FALL_REPORTER_TITLE_VALUES = [
  "Family member",
  "Caregiver (PCA, HHA, HCSS)",
  "Vendor (Insurance Plan)",
];

const NHTD_TBI_CASE_VALUES = ["NHTD", "TBI", "Other answer"];

export const INCIDENT_OPTION_COUNTS = {
  hospitalizationVendorContract: HOSPITALIZATION_VENDOR_CONTRACT_VALUES.length,
  deathVendor: DEATH_VENDOR_VALUES.length,
  hospitalName: HOSPITAL_NAME_VALUES.length,
  hospitalizationReason: HOSPITALIZATION_REASON_VALUES.length,
};

export const INCIDENT_OPTION_CATALOG = {
  hospitalizationVendorContract: toOptions(
    HOSPITALIZATION_VENDOR_CONTRACT_VALUES
  ),
  hcssContract: toOptions(["NHTD Waiver Service", "TBI WAIVER"]),
  deathVendor: toOptions(DEATH_VENDOR_VALUES),
  hospitalName: toOptions(HOSPITAL_NAME_VALUES),
  hospitalizationReason: toOptions(HOSPITALIZATION_REASON_VALUES),
  infectionType: toOptions(INFECTION_TYPE_VALUES),
  sourceOfInformation: toOptions(SOURCE_OF_INFORMATION_VALUES),
  fallAccidentType: toOptions(FALL_ACCIDENT_TYPE_VALUES),
  yesNoUnknown: toOptions(YES_NO_UNKNOWN_VALUES),
  yesNo: toOptions(YES_NO_VALUES),
  fallReporterTitle: toOptions(FALL_REPORTER_TITLE_VALUES),
  nhtdTbiCase: toOptions(NHTD_TBI_CASE_VALUES),
};
